import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {classify,sanitizeEvidence,persistAttribution} from '../netlify/functions/_shared/attribution.js';
const ctx={module:{exports:{}},URL,Date};vm.runInNewContext(fs.readFileSync('public/js/cashasis-attribution.js','utf8'),ctx);const {capture,safeUrl}=ctx.module.exports;
const now=Date.now(),time=new Date(now).toISOString();
const touch=(x={})=>({url:'https://www.cashasis.com/',referrer:'',at:time,...x});
const evidence=(a,b=a)=>({version:1,first:touch(a),latest:touch(b)});
for(const [name,data,result] of [
 ['Google click',{gclid:'test'},'google_ppc'],['braid',{wbraid:'test'},'google_ppc'],['Google UTM',{utm_source:'google',utm_medium:'cpc'},'google_ppc'],['Meta paid',{utm_source:'facebook',utm_medium:'paid_social'},'meta_paid'],['GHL Meta',{utm_source:'fb_ad'},'meta_paid'],['fbclid only',{fbclid:'test'},null],['organic',{referrer:'https://www.google.com/search'},'google_organic'],['direct',{},null],['spoofed Google',{referrer:'https://google.com.evil.test/'},null],['paid conflict',{gclid:'a',utm_source:'facebook',utm_medium:'paid_social'},null],['organic social',{utm_source:'facebook',utm_medium:'social'},null]
])test(name,()=>assert.equal(classify(touch(data)),result));
test('strip URL query and fragment',()=>assert.equal(safeUrl('https://www.cashasis.com/a?email=secret@example.com#token'),'https://www.cashasis.com/'));
test('internal CTA does not overwrite acquisition',()=>{const a=capture('https://www.cashasis.com/blog/a?gclid=abc','https://google.com/',null,now);const b=capture('https://www.cashasis.com/?utm_source=blog&utm_medium=cta','https://www.cashasis.com/blog/a',a,now+1000);assert.equal(b.latest.gclid,'abc');assert.equal(b.first.gclid,'abc');});
test('direct return preserves touch',()=>{const a=capture('https://www.cashasis.com/?gclid=abc','',null,now);const b=capture('https://www.cashasis.com/','',a,now+1000);assert.equal(b.latest.gclid,'abc');});
test('first and latest separate',()=>{const a=capture('https://www.cashasis.com/','https://www.google.com/',null,now);const b=capture('https://www.cashasis.com/?gclid=abc','',a,now+1000);assert.equal(classify(a.first),'google_organic');assert.equal(b.latest.gclid,'abc');assert.equal(b.first.gclid,undefined);});
test('invalid evidence refused',()=>assert.equal(sanitizeEvidence({version:1,first:touch({url:'https://evil.test/'}),latest:touch()}),null));
function fixture(c={}){const contact={id:'controlled',tags:[],customFields:[],email:'test@example.com',phone:'+17135550101',...c};const notes=[],calls=[];async function ghl(path,o={}){calls.push([path,o]);if(path.endsWith('/notes')){if(o.method==='POST')notes.push(JSON.parse(o.body));return {notes};}if(o.method==='PUT')Object.assign(contact,JSON.parse(o.body));if(path.endsWith('/tags')&&o.method==='POST')contact.tags.push(...JSON.parse(o.body).tags);return {contact};}return {contact,notes,calls,ghl};}
test('new paid attribution writes existing fields and tag; retry dedup',async()=>{const f=fixture(),body={email:f.contact.email,phone:f.contact.phone,attribution:evidence({gclid:'a'})};await persistAttribution({...f,body});assert.equal(f.contact.source,'Google PPC');assert.deepEqual(f.contact.tags,['source_google_ppc']);await persistAttribution({...f,body});assert.equal(f.notes.length,1);});
test('existing SalesGod source preserved',async()=>{const f=fixture({source:'SalesGod',tags:['salesgod_lead']});await persistAttribution({...f,body:{attribution:evidence({gclid:'a'})}});assert.equal(f.contact.source,'SalesGod');assert.deepEqual(f.contact.tags,['salesgod_lead']);});
test('existing native attribution untouched',async()=>{const native={sessionSource:'Organic Search'};const f=fixture({attributionSource:native});await persistAttribution({...f,body:{attribution:evidence({gclid:'a'})}});assert.equal(f.contact.attributionSource,native);assert(!f.calls.some(([p,o])=>o.body?.includes('attributionSource')));});
test('identity disagreement prevents all writes',async()=>{const f=fixture();const r=await persistAttribution({...f,body:{phone:'+17135550102',attribution:evidence({gclid:'a'})}});assert.equal(r.status,'identity_conflict');assert.equal(f.calls.length,0);});
test('unknown does not invent paid or organic',async()=>{const f=fixture();await persistAttribution({...f,body:{attribution:evidence({fbclid:'social'})}});assert.equal(f.contact.source,undefined);assert.deepEqual(f.contact.tags,[]);});
