import test from 'node:test';import assert from 'node:assert/strict';
import submit from '../netlify/functions/lead-submit.js';import update from '../netlify/functions/lead-update.js';
globalThis.Netlify={env:{get:k=>k.includes('GHL')?'controlled-token':''}};
const at=new Date().toISOString();const base={full_name:'Controlled Test',email:'controlled@example.com',phone:'+17135550101',address1:'100 Controlled Test Street',tcpa_consent:true,stage:'contact',attribution:{version:1,first:{url:'https://www.cashasis.com/',referrer:'',at,gclid:'controlled'},latest:{url:'https://www.cashasis.com/',referrer:'',at,gclid:'controlled'}}};
function request(b){return new Request('https://www.cashasis.com/.netlify/functions/lead-submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});}
let calls=[],notes=[],contact;
function setup(){calls=[];notes=[];contact={id:'test',email:base.email,phone:base.phone,tags:[],customFields:[]};globalThis.fetch=async(url,opt={})=>{calls.push([url,opt]);if(url==='controlled-token')return new Response('{}');if(url.includes('search/duplicate'))return Response.json({contact});if(url.endsWith('/notes')){if(opt.method==='POST')notes.push(JSON.parse(opt.body));return Response.json({notes});}if(url.endsWith('/tags')){contact.tags.push(...JSON.parse(opt.body).tags);return Response.json({tags:contact.tags});}if(url.endsWith('/contacts/test')){if(opt.method==='PUT')Object.assign(contact,JSON.parse(opt.body));return Response.json({contact});}throw Error('unexpected '+url);};}
test('validated submit forwards once and records attribution',async()=>{setup();const r=await submit(request({...base,attribution:undefined}));const j=await r.json();assert.equal(j.forwarded,true);assert.equal(j.attribution_status,'no_evidence');assert.equal(calls.filter(c=>c[0]==='controlled-token').length,1);assert.equal(contact.source,undefined);assert(!JSON.parse(calls.find(c=>c[0]==='controlled-token')[1].body).attribution);});
test('missing consent never calls upstream',async()=>{setup();const r=await submit(request({...base,tcpa_consent:false}));assert.equal(r.status,400);assert.equal(calls.length,0);});
test('invalid address never calls upstream',async()=>{setup();const j=await (await submit(request({...base,address1:'garbage'}))).json();assert.equal(j.filtered,true);assert.equal(calls.length,0);});
test('update attribution preserves condition and native data',async()=>{setup();contact.attributionSource={sessionSource:'native'};const r=await update(request({...base,attribution:undefined,property_condition:'Needs Work',selling_timeline:'30 Days',meta_event_id:'fixed'}));assert.equal(r.status,200);assert.equal(contact.attributionSource.sessionSource,'native');assert.equal(contact.source,undefined);});
test('conflicting identity rejects update',async()=>{setup();const r=await update(request({...base,phone:'+17135550102'}));assert.equal(r.status,409);assert.equal(calls.filter(c=>c[1].method==='PUT').length,0);});
