import test from 'node:test';import assert from 'node:assert/strict';
import {conditionTimelinePatch} from '../netlify/functions/_shared/condition-timeline.js';
import {publishedProduction,createStoreView} from '../netlify/functions/_shared/attribution-queue.js';
import submit from '../netlify/functions/lead-submit.js';import update from '../netlify/functions/lead-update.js';
test('blank/missing/null details never produce destructive writes',()=>{for(const body of [{},{property_condition:'',selling_timeline:'  '},{property_condition:null,selling_timeline:undefined}])assert.deepEqual(conditionTimelinePatch(body),[]);});
test('complete authoritative details update exact fields',()=>assert.equal(conditionTimelinePatch({stage:'qualified',property_condition:'Needs Work',selling_timeline:'30 Days'}).length,2));
test('new valid final choices replace existing details',()=>assert.deepEqual(conditionTimelinePatch({stage:'qualified',property_condition:'Move-In Ready',selling_timeline:'ASAP'}).map(x=>x.fieldValue),['Move-In Ready','ASAP']));
test('one blank field preserves it while valid completed field updates',()=>assert.deepEqual(conditionTimelinePatch({stage:'qualified',property_condition:'',selling_timeline:'60-90 Days'}).map(x=>x.fieldValue),['60-90 Days']));
test('non-final and invalid values rejected',()=>{assert.throws(()=>conditionTimelinePatch({stage:'contact',property_condition:'Needs Work'}),/final_details_required/);assert.throws(()=>conditionTimelinePatch({stage:'qualified',property_condition:'null'}),/invalid_property_condition/);});
test('only current published production context accepted',()=>{assert(publishedProduction({deploy:{context:'production',published:true}}));for(const c of [undefined,{deploy:{context:'production',published:false}},{deploy:{context:'deploy-preview',published:true}}])assert.equal(publishedProduction(c),false);});
test('preview handlers fail before any network mutation',async()=>{let calls=0;globalThis.fetch=async()=>{calls++;throw Error('must not run')};const req=()=>new Request('https://example.test',{method:'POST',body:'{}'});for(const h of [submit,update])assert.equal((await h(req(),{deploy:{context:'deploy-preview',published:false}})).status,503);assert.equal(calls,0);});
class Store{constructor(){this.m=new Map;this.n=0;}async get(k){return this.m.get(k)?.data??null;}async getWithMetadata(k){return this.m.get(k)??null;}async setJSON(k,v,o={}){const old=this.m.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};const etag=String(++this.n);this.m.set(k,{data:structuredClone(v),etag});return {modified:true,etag};}async delete(k){this.m.delete(k);}async *list(){yield {blobs:[...this.m.keys()].map(key=>({key}))};}}
test('legacy receipt and claims migrate without overwrite',async()=>{const a=new Store,b=new Store;await b.setJSON('claims/qa',{receiptId:'old'});await b.setJSON('pending/old',{status:'pending'});const s=createStoreView(a,[b]);assert.equal((await s.get('claims/qa')).receiptId,'old');assert.equal((await s.setJSON('claims/qa',{receiptId:'new'},{onlyIfNew:true})).modified,false);assert.equal((await s.getWithMetadata('pending/old')).data.status,'pending');});
test('legacy active lease stays active; CAS uses new etag',async()=>{const a=new Store,b=new Store;await b.setJSON('locks/qa',{token:'old',until:9999999999999});const s=createStoreView(a,[b]);const v=await s.getWithMetadata('locks/qa');assert.equal(v.data.token,'old');assert.equal((await s.setJSON('locks/qa',{token:'new',until:0},{onlyIfMatch:v.etag})).modified,true);});
test('completed records kept, pending cleanup removes both copies',async()=>{const a=new Store,b=new Store;await b.setJSON('pending/qa',{id:'qa'});await b.setJSON('completed/qa',{status:'recorded'});const s=createStoreView(a,[b]);await s.get('pending/qa');await s.delete('pending/qa');assert.equal(await s.get('pending/qa'),null);await assert.rejects(s.delete('completed/qa'));assert.equal((await s.get('completed/qa')).status,'recorded');});
