import test from 'node:test';import assert from 'node:assert/strict';
import {queueAttribution,markReady,processReceipt,preflight} from '../netlify/functions/_shared/attribution-queue.js';
class MemoryStore{constructor(){this.m=new Map;this.seq=0;}async get(k){return structuredClone(this.m.get(k)?.data??null);}async getWithMetadata(k){return structuredClone(this.m.get(k)??null);}async setJSON(k,v,o={}){const old=this.m.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};const etag=String(++this.seq);this.m.set(k,{data:structuredClone(v),etag});return {modified:true,etag};}async delete(k){this.m.delete(k);}}
const at=new Date().toISOString();const body=(extra={})=>({email:'qa@example.invalid',phone:'+12025550101',attribution:{version:1,first:{url:'https://www.cashasis.com/',referrer:'',at,...extra},latest:{url:'https://www.cashasis.com/',referrer:'',at,...extra}}});
function crm(){const c={id:'qa',email:'qa@example.invalid',phone:'+12025550101',tags:[],customFields:[]},notes=[];let found=true,noteFail=false;const api=async(p,o={})=>{if(p.includes('search/duplicate'))return {contact:found?structuredClone(c):null};if(p.endsWith('/notes')){if(o.method==='POST'){notes.push(JSON.parse(o.body));if(noteFail)throw Error('response_lost');}return {notes:structuredClone(notes)};}if(p.endsWith('/tags')){for(const t of JSON.parse(o.body).tags)if(!c.tags.includes(t))c.tags.push(t);return {tags:c.tags};}if(o.method==='PUT'){const patch=JSON.parse(o.body);Object.assign(c,patch);}return {contact:structuredClone(c)};};return {c,notes,api,setFound:v=>found=v,setNoteFail:v=>noteFail=v};}
test('durable queue retries delayed creation without losing capture',async()=>{const s=new MemoryStore,f=crm();f.setFound(false);const id=await queueAttribution(body({gclid:'qa'}),s);assert.equal((await processReceipt(id,s,f.api)).status,'awaiting_intake');await markReady(id,s);assert.equal((await processReceipt(id,s,f.api)).status,'pending_contact_creation');f.setFound(true);assert.equal((await processReceipt(id,s,f.api)).status,'recorded');assert.equal(f.c.source,'Google PPC');assert.equal(await s.get('pending/'+id),null);assert.equal((await s.get('completed/'+id)).email,undefined);});
test('concurrent conflicting receipts never create competing tags',async()=>{const s=new MemoryStore,f=crm();const a=await queueAttribution(body({gclid:'qa'}),s),b=await queueAttribution(body({utm_source:'facebook',utm_medium:'paid_social'}),s);await markReady(a,s);await markReady(b,s);await Promise.all([processReceipt(a,s,f.api),processReceipt(b,s,f.api)]);await processReceipt(b,s,f.api);assert.equal(f.c.source,'Google PPC');assert.deepEqual(f.c.tags,['source_google_ppc']);});
test('concurrent identical receipts generate one note',async()=>{const s=new MemoryStore,f=crm();const id=await queueAttribution(body({gclid:'qa'}),s);await markReady(id,s);await Promise.all([processReceipt(id,s,f.api),processReceipt(id,s,f.api)]);await processReceipt(id,s,f.api);assert.equal(f.notes.length,1);});
test('lost note response reads existing note without duplicate',async()=>{const s=new MemoryStore,f=crm();const id=await queueAttribution(body({gclid:'qa'}),s);await markReady(id,s);f.setNoteFail(true);await assert.rejects(processReceipt(id,s,f.api));f.setNoteFail(false);assert.equal((await processReceipt(id,s,f.api)).status,'recorded');assert.equal(f.notes.length,1);});
test('preflight rejects identity conflict before mutations',async()=>{const f=crm();await assert.rejects(preflight({...body(),phone:'+12025550102'},f.api),/identity_conflict/);assert.equal(f.c.source,undefined);});
